docs: next version needs to match keystone (#7003)
* docs: next version needs to match keystone

- fixes #6847, #6848 
- in case your next version does not match with the one from keystone
  you will see errors such as 
  ```
  TypeError: Cannot destructure property 'inAmpMode' of '(0 , _react).useContext(...)' as it is null.
  ```

* update path and copy

Co-authored-by: Daniel Cousens <413395+dcousens@users.noreply.github.com>